application: tiny-blogs
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /
  script: code.url.app
  secure: always

- url: /login
  script: code.url.app
  secure: always

- url: /register
  script: code.url.app
  secure: always

- url: /.*
  script: code.url.app
  secure: never



libraries:
- name: jinja2
  version: latest
